var slidBox=new function(){this.configAnimationSpeed=1000;this.loadingImage='./slidBox/images/loading.gif';this.configHorizontalMargin=0.1;this.configPreloadSet=false;this.loadingWidth;this.loadingHeight;this.init=function(){slidBox.install();var loading=new Image();$(loading).load(function(){$(this).removeAttr("width").removeAttr("height").css({width:"",height:""});slidBox.loadingWidth=this.width;slidBox.loadingHeight=this.height;}).attr('src',slidBox.loadingImage);$(window).resize(function(){slidBox.refresh();});};this.hidePageContent=false;this.initialScroll;this.start=function(){var rel=$(this).attr('rel');if(rel=='slidBox'){slidBox.add($(this),true);}
else{var foc=$(this);$('a[rel='+rel+']').each(function(){slidBox.add($(this),($(this).context==$(foc).context));});}
if(navigator.userAgent.match(/iPad/i)!=null||navigator.userAgent.match(/iPod/i)!=null||navigator.userAgent.match(/iPhone/i)!=null||navigator.userAgent.match(/Android/i)!=null){slidBox.hidePageContent=true;slidBox.initialScroll=$(document).scrollTop();$('body').children().hide();}
$('#sb_container').show().css('opacity',0).animate({opacity:1.0},300,'swing');slidBox.refresh();return false;};this.end=function(){if(slidBox.hidePageContent){$('body').children().show();slidBox.hidePageContent=false;setTimeout(function(){$(document).scrollTop(slidBox.initialScroll);},200);}
$('#sb_container').animate({opacity:0},200,'swing',function(){$('#sb_container').hide();$('li','#sb_container').remove();});};this.click=function(event){if($(event.target).attr('id')=='sb_focus'||$(event.target).hasClass('sb_viewer')){slidBox.end();return;}
var target=$(event.target);if($(event.target).hasClass('sb_item')){slidBox.setfocus($(event.target).find('img.sb_image'));slidBox.refocus(true);return;}
if($(event.target).hasClass('sb_image')){slidBox.setfocus($(event.target));slidBox.refocus(true);return;}
slidBox.end();return false;};this.previousKey;this.acceptPreviousKey=true;this.keydown=function(e){var keyCode=e.keyCode||e.which;var key={j:74,k:75,left:37,up:38,right:39,down:40,enter:13,escape:27,spacebar:32,backspace:8};if(slidBox.previousKey==keyCode&&slidBox.acceptPreviousKey==false)
return;var newfocus;switch(keyCode){case key.left:case key.k:case key.backspace:newfocus=$('#sb_focus').parent().parent().prev().find('img.sb_image');if($(newfocus).length==0){$('ul',"#sb_container").each(function(){slidBox.refocus(false);slidBox.hideCaption();}).animate({left:'+=50px'},100,'swing').animate({left:'-=50px'},200,'swing',function(){slidBox.showCaption(true)});}
break;case key.right:case key.j:case key.spacebar:newfocus=$('#sb_focus').parent().parent().next().find('img.sb_image');$('ul',"#sb_container").each(function(){slidBox.refocus(false);slidBox.hideCaption();}).animate({left:'-=50px'},100,'swing').animate({left:'+=50px'},200,'swing',function(){slidBox.showCaption(true)});break;case key.escape:slidBox.end();return;}
slidBox.previousKey=keyCode;slidBox.acceptPreviousKey=false;setTimeout(function(){slidBox.acceptPreviousKey=true;},200);if($(newfocus).length){slidBox.setfocus($(newfocus));slidBox.refocus(true);}
return;};this.dragOrigin;this.dragPrevious;this.dragStart=function(jquery_event){e=jquery_event.originalEvent;if(!$(jquery_event.target).hasClass('sb_image')&&!$(jquery_event.target).hasClass('sb_item')){return;}
if(e.touches.length==1){slidBox.dragPrevious=slidBox.dragOrigin=e.touches[0].pageX;document.addEventListener('touchmove',slidBox.drag,false);document.addEventListener('touchend',slidBox.dragEnd,false);slidBox.hideCaption();return false;}};this.drag=function(e){e.preventDefault();var newLeft=parseInt($('ul','#sb_container').css('left'));newLeft-=slidBox.dragPrevious-e.touches[0].pageX;$('ul',"#sb_container").stop(true).css({left:newLeft});var frameVelocity=e.touches[0].pageX-slidBox.dragPrevious;var previousVelocity=slidBox.dragPrevious-slidBox.dragOrigin;var directionChange=frameVelocity*previousVelocity;if(directionChange<0)
slidBox.dragOrigin=slidBox.dragPrevious;slidBox.dragPrevious=e.touches[0].pageX;return false;};this.dragEnd=function(e){document.removeEventListener('touchmove',slidBox.drag,false);document.removeEventListener('touchend',slidBox.dragEnd,false);var threshold=50;var direction=slidBox.dragOrigin-slidBox.dragPrevious;if(direction>threshold){$('#sb_focus').parent().parent().next().find('img.sb_image').each(function(){slidBox.setfocus($(this));});}
else if(direction<-threshold){$('#sb_focus').parent().parent().prev().find('img.sb_image').each(function(){slidBox.setfocus($(this));});}
slidBox.refocus(true);return false;};this.install=function(){var content='<div id="sb_container" style="position:fixed;left:0;right:0;overflow:visible;white-space:nowrap;z-index:525;top:10%;bottom:10%;font-family:Helvetica;font-size:12px;">'+'<span id="sb_background" style="position:fixed;top:0;bottom:0;left:0;right:0;background-color:#334;opacity:0.8;"></span>'+'<ul style="position:absolute;height:100%;margin:0;padding:0;"></ul>'+'<span id="sb_close" style="position:fixed;top:0;right:5%;background-color:white;font-size:16px;color:#334;padding:5px;cursor:pointer;">Close</span>'+'</div>';$('body').append(content);$('#sb_container').hide();$('a[rel^=slidBox]').click(slidBox.start);$("#sb_background").click(slidBox.end);$("#sb_close").click(slidBox.end);$('ul',"#sb_container").click(function(e){slidBox.click(e)});$(document).keydown(function(e){slidBox.keydown(e)});$("#sb_container").bind('touchstart',function(e){slidBox.dragStart(e);});};this.add=function(e,f){var content=$('<li class="sb_item" style="display:inline-block;height:100%;vertical-align:middle;white-space:normal;">'+'<div class="sb_img_container" style="position:relative;">'+'<img class="sb_image" src="'+slidBox.loadingImage+'" style="margin-left:0;margin-right:0;" />'+'<span class="sb_caption" style="position:absolute;left:0;right:0;bottom:0px;width:100%;background-color:white;opacity:0;"></span>'+'<span class="sb_overlay"></span>'+'</div>'+'</li>');$('ul','#sb_container').append(content);$(content).find('img.sb_image').data('width',slidBox.loadingWidth).data('height',slidBox.loadingHeight).data('src',$(e).attr('href')).data('status','off').data('caption',$(e).attr('title'));if($(content).prev().hasClass('sb_viewer'))
$(content).addClass('sb_next');if($(content).next().hasClass('sb_viewer'))
$(content).addClass('sb_prev');if(f)slidBox.setfocus($(content).find('img.sb_image'));};this.setfocus=function(i){if($(i).length==0)
return;$('li','#sb_container').removeClass('sb_prev').removeClass('sb_next');$('#sb_focus').parent().parent().removeClass('sb_viewer');$('#sb_focus').attr('id','');var p=$(i).parent().parent();$(p).addClass('sb_viewer');$(p).next().addClass('sb_next');$(p).prev().addClass('sb_prev');$(i).attr('id','sb_focus');};this.refreshImage=function(i){var imgWidth=$(i).data('width');var imgHeight=$(i).data('height');var p=$(i).parent();var pp=$(p).parent();$(i).width(imgWidth);$(i).height(imgHeight);$(p).width($(i).outerWidth());$(p).height($(i).outerHeight());sizeRatio=imgWidth/imgHeight;if($(i).outerWidth()>$(pp).innerWidth()){$(i).width(Math.round($(pp).innerWidth()-($(p).outerWidth()-$(i).width())));$(i).height(Math.round($(i).width()/sizeRatio));}
if($(i).outerHeight()>$(pp).innerHeight()){$(i).height(Math.round($(pp).innerHeight()-($(p).outerHeight()-$(i).height())));$(i).width(Math.round($(i).height()*sizeRatio));}
$(p).width($(i).outerWidth());$(p).height($(i).outerHeight());var newMargin=($(pp).innerHeight()-$(p).outerHeight())/2;$(p).css({marginTop:newMargin,marginBottom:0});newMargin=($(pp).innerWidth()-$(p).outerWidth())/2;$(p).stop(true).css({marginLeft:newMargin,marginRight:newMargin});if($(pp).hasClass('sb_prev')){newMargin=$(pp).innerWidth()-$(p).outerWidth();$(p).stop(true).css({marginLeft:newMargin,marginRight:0});}
if($(pp).hasClass('sb_next')){var newMargin=$(pp).innerWidth()-$(p).outerWidth();$(p).stop(true).css({marginRight:newMargin,marginLeft:0});}};this.refresh=function(){$("#sb_container").find("li").width($(window).width()*(1.0-slidBox.configHorizontalMargin*2));$('img.sb_image',"#sb_container").each(function(){slidBox.refreshImage($(this))});slidBox.refocus(false);};this.refocus=function(animate){viewer_width=$(window).width()*(1.0-slidBox.configHorizontalMargin*2);if($('li','#sb_container').length==0)
return;if($('#sb_focus').length==0)
slidBox.setfocus($('img.sb_image',"#sb_container").first());slidBox.hideCaption();var div=$('#sb_focus').parent();var li=$(div).parent();var prev=$(li).prev().find('div.sb_img_container');var next=$(li).next().find('div.sb_img_container');var newLeft=(($(window).width()-viewer_width)/2)-$(li).position().left;var newMargin=($(li).innerWidth()-$('#sb_focus').outerWidth())/2;var newMarginPrev=$(li).prev().innerWidth()-$(prev).outerWidth();var newMarginNext=$(li).next().innerWidth()-$(next).outerWidth();if(animate){$('ul',"#sb_container").stop(true).animate({left:newLeft},slidBox.configAnimationSpeed,'swing',function(){slidBox.showCaption()});$(div).stop(true).animate({marginLeft:newMargin,marginRight:newMargin},slidBox.configAnimationSpeed,'swing');$(li).stop(true).animate({opacity:1.0},slidBox.configAnimationSpeed,'swing');$(prev).stop(true).animate({marginLeft:newMarginPrev,marginRight:0},slidBox.configAnimationSpeed,'swing');$(prev).parent().stop(true).animate({opacity:0.5},slidBox.configAnimationSpeed,'swing');$(next).stop(true).animate({marginRight:newMarginNext,marginLeft:0},slidBox.configAnimationSpeed,'swing');$(next).parent().stop(true).animate({opacity:0.5},slidBox.configAnimationSpeed,'swing');}else{$('ul',"#sb_container").stop(true).css({left:newLeft});$(div).stop(true).css({marginLeft:newMargin,marginRight:newMargin});$(li).stop(true).css({opacity:1.0});$(prev).stop(true).css({marginLeft:newMarginPrev,marginRight:0});$(prev).parent().stop(true).css({opacity:0.5});$(next).stop(true,true).css({marginRight:newMarginNext,marginLeft:0});$(next).parent().stop(true).css({opacity:0.5});slidBox.showCaption();}
slidBox.load($('#sb_focus'));};this.hideCaption=function(){$('.sb_caption','#sb_container').stop(true).animate({opacity:0},200,'swing');};this.showCaption=function(){var caption=$('#sb_focus').data('caption');if(caption=='')
return;var e=$('#sb_focus').parent().find('.sb_caption');$(e).html('<p style="margin:10px;">'+caption+'</p>');if($('#sb_focus').data('status')!='ok')
return;$(e).stop(true).animate({opacity:1.0},200,'swing');};this.load=function(i){if($(i).data('status')=='loading'||$(i).data('status')=='ok'){slidBox.preload();return;}
$(this).data('status','loading');var tmp=new Image();$(tmp).data(i).load(function(){$(this).removeAttr("width").removeAttr("height").css({width:"",height:""});var img=$(this).data();var li=$(img).parent().parent();var opa=0;if($(li).hasClass('sb_prev')||$(li).hasClass('sb_next')){opa=0.5;}
else if($(img).attr('id')=='sb_focus'){opa=1.0;}
$(img).data('width',this.width).data('height',this.height).data('status','ok').width(this.width).height(this.height).attr('src',$(this).attr('src')).css({padding:10,backgroundColor:'white'});$(li).addClass('sb_loaded').stop(true).css({opacity:0}).animate({opacity:opa},slidBox.configAnimationSpeed,'swing');slidBox.refreshImage($(img));if($(img).attr('id')=='sb_focus')
slidBox.showCaption();slidBox.preload();}).attr('src',$(i).data('src'));};this.preload=function(){var li=$('#sb_focus').parent().parent();var next=$(li).next().find('img.sb_image');if($(next).data('status')=='off'){slidBox.load($(next));return;}
var prev=$(li).prev().find('img.sb_image');if($(prev).data('status')=='off'){slidBox.load($(prev));return;}
if(slidBox.configPreloadSet){$('img.sb_image','#sb_container').each(function(){if($(this).data('status')=='off'){slidBox.load($(this));return false;}});}};};